export const FETCH_RANDOM_MOVIES = 'FETCH_RANDOM_MOVIES';
export const FETCH_MOVIE_INFO = 'FETCH_MOVIE_INFO';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const ERROR_LOADING = 'ERROR_LOADING';
